repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5 # run `pre-commit autoupdate` to automatically use the latest version
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format